import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import styles from "./layout.module.scss";
import moment from "moment";
import Footer from "@/app/Footer";
import React from "react";
import { useRouter } from "next/navigation";
import TodoListContextProvider from "@/app/TodoListContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{
          height: "100vh",
        }}
      >
        <header className={styles.header}>header</header>
        <main className={styles.main}>
          <TodoListContextProvider content={children} />
        </main>
        <footer className={styles.footer}>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
