import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import styles from "./styles/layout.module.scss";
import Footer from "@/app/Footer";
import React from "react";
import TodoListContextProvider from "@/app/list/TodoListContextProvider";
import { Bell, Settings } from "react-feather";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>
        <header className={styles.header}>
          <nav>
            <a href="#">
              <Bell size={35} />
            </a>
            <a href="#">
              <Settings size={35} />
            </a>
          </nav>
        </header>
        <main className={styles.main}>
          <TodoListContextProvider content={children} />
        </main>
        <footer className={styles.footer}>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
