name: "lint and build"

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [x64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Frontend
        run: |
          yarn install
          yarn lint

      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
      - name: Lint Rust Backend
        run: |
          cd src-tauri 
          cargo clippy -- -D warnings -W clippy::pedantic 
          cd ..

  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        os: [ubuntu-latest]
        arch: [x64]
    steps:
      - name: Build Tauri App
        run: yarn tauri build

