name: "lint and build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Frontend
        run: |
          yarn install
          yarn lint

      - name: Setup Rust
        uses: actions/setup-rust@v1

      - name: Lint Rust Backend
        run: cargo clippy -- -D warnings -W clippy::pedantic

      - name: Build Tauri App
        run: cargo tauri build

